"""empty message

Revision ID: a190b2c353ba
Revises: 299036a7f8fb
Create Date: 2022-07-30 06:30:54.667679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a190b2c353ba'
down_revision = '299036a7f8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('url', sa.String(length=250), nullable=False))
    op.drop_column('task', 'done')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.add_column('task', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('task', 'url')
    # ### end Alembic commands ###
